
dist: trusty

language: cpp

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update
  - sudo aptitude search qca
  - sudo aptitude search qt5
  - sudo aptitude search qmake
  - sudo apt-get install -y make
  - sudo apt-get install -y libqca2-dev
  - sudo apt-get install -y qt5-default
  - sudo apt-get install -y qt5-qmake
  # qt5-qmake qt5-default libqca-qt5-2-dev libqca2-dev make

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script: cd config && qmake && make && cd ../usermanager && qmake && make
