
dist: xenial

language: cpp

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.0-xenial
  - sudo apt-get update
  - sudo aptitude search qca
  - sudo aptitude search qt5
  - sudo aptitude search qmake
  # - http://download.qt.io/official_releases/qt/5.12/5.12.0/qt-opensource-linux-x64-5.12.0.run
  - sudo apt-get install -y make
  - sudo apt-get install -y qt512base
  - sudo apt-get install -y libqca2-dev
  # - sudo apt-get install -y qt5-qmake
  - . /opt/qt512/bin/qt512-env.sh
  # qt5-qmake qt5-default libqca-qt5-2-dev libqca2-dev make

matrix:
  fast_finish: true
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script: . /opt/qt512/bin/qt512-env.sh && cd config && qmake && make && cd ../usermanager && qmake && make
